#!/bin/bash

## Copyright (C) 2019 - 2019 Patrick Schleizer <adrelanos@riseup.net>
## See the file COPYING for copying conditions.

## Disable debugging since we do not want random and secure_tcp_seq in systemd
## journal log.
#set -x

set -e

test -e /dev/random || exit 2
test -f /proc/kallsyms || exit 3

command -v hexdump >/dev/null || exit 4
command -v grep >/dev/null || exit 5
command -v awk >/dev/null || exit 6

## https://stackoverflow.com/a/34329057
## https://www.whonix.org/wiki/Dev/Entropy#Viewpoint:_better_use_.2Fdev.2Frandom
## https://forums.whonix.org/t/dev-random-vs-dev-urandom/8571
random="$(hexdump -n 16 -e '4/4 "%08X" 1 "\n"' /dev/random)" || exit 7

if [ "$random" = "" ]; then
   exit 8
fi

string_length_of_random="${#random}"

if [ ! "$string_length_of_random" = "32" ]; then
   exit 9
fi

old_kptr_restrict="$(sysctl -n kernel.kptr_restrict)" || error_code=10

if [ "$old_kptr_restrict" = "2" ]; then
   sysctl -w kernel.kptr_restrict=1 >/dev/null || exit 11
   re_enable=true
fi

secure_tcp_seq="$(grep "T secure_tcp_seq" /proc/kallsyms | awk -F ' ' '{print $1}')" || exit 12

if [ "$secure_tcp_seq" = "" ]; then
   exit 13
fi

string_length_of_secure_tcp_seq="${#secure_tcp_seq}"

if [ "$string_length_of_secure_tcp_seq" -lt "16" ]; then
   exit 14
fi

if [ "$re_enable" = "true" ]; then
   sysctl -w kernel.kptr_restrict=2 >/dev/null || error_code=15
fi

if [ "$secure_tcp_seq" = "0000000000000000" ]; then
   error_code=16
   exit "$error_code"
fi

modprobe tirdad _seq_secret="$random" _tcp_secure_seq_adr="$secure_tcp_seq" || error_code=17

if [ ! "$error_code" = "" ]; then
   exit "$error_code"
fi
